db_type: "sql"
db_host: "localhost"
db_port: "3306"
db_user: "root"
db_password: "password"
db_name: "ethereum_listener"
ethereum_url: "wss://eth-sepolia.g.alchemy.com/v2/25Rl8mnE77awqRL1XfinQx2jn2wl3bnk"
